import Head from "next/head";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css"></link>
      </Head>
      <div className="bootstrap-icons">
        <div className="text-center">
          <a href="https://www.linkedin.com/in/dhanar98/">
            <i className="bi bi-linkedin"></i>linkedin
          </a>
          <a href="https://github.com/dhanar98">
            <i className="bi bi-github"></i>Github
          </a>
        </div>
      </div>
    </div>
  );
}
